name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python ebooksapi/manage.py test

  deploy:

    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Deploy in AWS
      env:
        PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
        HOSTNAME: ${{ secrets.HOSTNAME }}
        USER_NAME: ${{ secrets.USER_NAME }}

      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

          #We connected to AWS instance and we start deployment to the server
          cd /home/ec2-user/test_project/session3 &&
          git checkout main &&
          git fetch --all &&
          git reset --hard origin/main &&
          git pull origin main
        '
      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Application
        run: |
          python ebooksapi/manage.py runserver 0.0.0.0:8000
      

      

